const CHAIN = {
  Ethereum: 'Ethereum',
  Solana: 'Solana',
  Polygon: 'Polygon',
};
export const top_sellers = [
  {
    name: 'Crispin Berry',
    price: '214.2 ETH',
    img: 'images/avt-4.jpg',
    chain: CHAIN.Ethereum,
    number: '1',
    color: 'red',
  },
  {
    name: 'Crispin Berry',
    price: '214.2 ETH',
    img: 'images/avt-4.jpg',
    chain: CHAIN.Solana,
    number: '2',
    color: 'blue',
  },
  {
    name: 'Crispin Berry',
    price: '214.2 ETH',
    img: 'images/avt-4.jpg',
    chain: CHAIN.Polygon,
    number: '3',
    color: 'green',
  },
  {
    name: 'Crispin Berry',
    price: '214.2 ETH',
    img: 'images/avt-4.jpg',
    chain: CHAIN.Polygon,
    number: '4',
    color: 'green',
  },
  {
    name: 'Crispin Berry',
    price: '214.2 ETH',
    img: 'images/avt-4.jpg',
    chain: CHAIN.Polygon,
    number: '5',
    color: 'green',
  },
];

export const top_collection = [
  { number: '1', color: 'red' },
  { number: '2', color: 'blue' },
  { number: '3', color: 'green' },
  { number: '4', color: 'purple' },
  { number: '5', color: 'yellow' },
  { number: '6', color: 'red' },
  { number: '7', color: 'blue' },
  { number: '8', color: 'green' },
  { number: '9', color: 'purple' },
  { number: '10', color: 'yellow' },
  { number: '1', color: 'red' },
  { number: '2', color: 'blue' },
  { number: '3', color: 'green' },
  { number: '4', color: 'purple' },
  { number: '5', color: 'yellow' },
  { number: '6', color: 'red' },
  { number: '7', color: 'blue' },
  { number: '8', color: 'green' },
  { number: '9', color: 'purple' },
  { number: '10', color: 'yellow' },
];
