exports.adminService = require('./adminService');
exports.categoryService = require('./categoryService');
exports.suggestionService = require('./suggestionService');
exports.verificationServices = require('./verificationServices');
exports.partnerServices = require('./partnerServices');
exports.nftteamsService = require('./nftteamsService');
exports.createCollectionService = require('./createCollectionService');
exports.signupServices = require('./signupServices');
exports.blockchainService = require('./blockchainService');
exports.searchServices = require('./searchService');
exports.historyServices=require('./historyService')
exports.subscriptionService=require('./subscriptionService')
exports.orderServices = require('./orderServices')
exports.bidServices = require("./bidServices")
exports.reportService = require("./reportService")
exports.reportedUserService = require("./reportedUserServices")
