export const HOME = "/"
export const EXPLORE = "/explore"
export const EXPLORENFT = "/explorenft"
export const ACTIVITY = "/activity"
export const HOWITWORKS = "/howitworks"
export const CREATENEWITEM = "/createnewitem"
export const PROFILE = "/profile"
export const OtherUser = "/users/:id"
export const TERMSCONDITION = "/termscondition"
export const PRIVACY = "/privacy"
export const PARTNERS = "/partners"
export const HELPCENTER = "/helpcenter"
export const TOPSELLER = "/topseller"
export const TOPCOLLECTIONCARD = "/topcollectioncard"
export const EXPLOREDETAIL = "/exploredetail/:id"
export const EXPLOREFILTER = "/explorefilter/:id"
export const WALLETLOGIN = "/walletlogin"
export const PROFILESETTING = "/profilesetting"
export const BLOG = "/blog"
//Wait fro Veriification
export const WAIT = "/wait"

// export const BLOGDETAIL = "/blogdetail"
export const BLOGDETAIL = "/blogdetail/:id"
export const LOGIN = "/login"
export const REGISTER = "/register"
export const REGISTRATION_VERIFY = "/register_verify"
export const LOGIN_VERIFY = "/login_verify"
export const MAGICLINK = "/magicLink"
export const COLLECTIABLES = "/collectibles"
export const LIVEAUCTION = "/liveaction"
export const ABOUT = "/about"
export const MYCOLLECTIONS = "/mycollections"
export const SUGGESTIONS = "/suggestions"
export const BECOMEPARTNER = "/becomepartner"
export const DROPDETAIL = "/dropdetail"
export const APPLYVERIFICATION = "/applyverification"
export const REQUESTFORM = "/requestform"
export const REWARDS = "/rewards"
export const FAVORITES = "/favorites"
export const GETLISTED = "/getlisted"
export const STEPTWO = "/steptwo"

// EXPLORE LINKS
export const EXPLORE_SOL = "/explore-solana"
export const EXPLORE_ETH = "/explore-ethereum"
export const EXPLORE_BINANCE = "/explore-binance"
export const EXPLORE_HARMONY = "/explore-harmony"
export const EXPLORE_POLYGON = "/explore-polygon"




